<?php

/**
 * @file
 *
 */

/**
 * Implements hook_install().
 */
function registration_dev_install() {
  include_once DRUPAL_ROOT . '/profiles/minimal/minimal.install';
  minimal_install();

  // Enable the admin theme.
  db_update('system')
    ->fields(array('status' => 1))
    ->condition('type', 'theme')
    ->condition('name', 'seven')
    ->execute();
  variable_set('admin_theme', 'seven');
  variable_set('node_admin_theme', '1');
}

/**
 * Setup registration stuff.
 */
function registration_dev_setup() {
  registration_type_save(new RegistrationType(array(
    'name' => 'registration_type_1',
    'label' => 'Registration Type 1'
  )));

  // create event content type
  $types = array(
    array(
      'type' => 'event',
      'name' => st('Event'),
      'base' => 'node_content',
      'description' => st("An event that you can register for."),
      'custom' => 1,
      'modified' => 1,
      'locked' => 0,
    ),
    array(
      'type' => 'post',
      'name' => st('Post'),
      'base' => 'node_content',
      'description' => st("Content posted into a group."),
      'custom' => 1,
      'modified' => 1,
      'locked' => 0,
    ),
  );

  foreach ($types as $type) {
    $type = node_type_set_defaults($type);
    node_type_save($type);
    node_add_body_field($type);
  }

  field_create_field(array(
    'field_name' => 'field_registration',
    'type' => 'registration'
  ));

  field_create_instance(array(
    'field_name' => 'field_registration',
    'entity_type' => 'node',
    'bundle' => 'event',
    'label' => 'Registration'
  ));

  $node = new stdClass();
  $node->type = 'event';
  node_object_prepare($node);
  $node->title = 'Test Event';
  $node->body = devel_create_content();
  $node->uid = 1;
  $node->field_registration[LANGUAGE_NONE][0]['registration_type'] = 'registration_type_1';
  node_save($node);

  $settings = array(
    'status' => TRUE,
    'capacity' => 0,
    'send_reminder' => 0,
    'settings' => serialize(array(
      'from_address' => 'info@thinkshout.com'
    )),
    'open' => NULL,
    'close' => NULL,
  );
  registration_update_entity_settings('node', $node->nid, $settings);
}
